application:
  message: hello, otdd
server:
  port: 8080

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO

plugin:
  pluginList:
    - pluginName: otdd http plugin
      description: the otdd official http plugin. it parses http bytes back and from ddl. supports http/1.0 and http/1.1
      pluginVersion: 0.1.0
      protocol: http
      downloadUrl: https://otdd.io/plugins/ddl-plugin-http-0.1.0-plugin.jar
    - pluginName: otdd thrift plugin
      description: the otdd official thrift plugin. it parses thrift bytes back and from ddl.
      pluginVersion: 0.1.0
      protocol: thrift
      downloadUrl: https://otdd.io/plugins/ddl-plugin-thrift-0.1.0-plugin.jar
